In [2]:
import numpy as np

# Input array

In [4]:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
print(X)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]


# Output (Response Variable)

In [3]:
y=np.array([[1],[1],[0]])

# Sigmoid Function

In [5]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

# Derivative of Sigmoid Function

In [6]:
def derivatives_sigmoid(x):
    return x * (1 - x)

# Variable initialization

In [8]:
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

# weight and bias initialization

In [9]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

# Forwards and Back propagation

In [11]:
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)
    
    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

# Output

In [12]:
print(output)

[[ 0.984547  ]
 [ 0.96752964]
 [ 0.04394892]]


 Output above 0.5 is classified as 1 and others are classified as 0